### ISSUE TITLE
"Sorry, the board list cannot be received"

### ISSUE THREAD

**Issue by Tibb** [miroapp/sketch_plugin#20]
Mac OS version: 12.1
Sketch version: 83.1
Miro plugin version: 1.6.2

Hi, it is not possible anymore to sync Sketch artboards on Miro boards.

Steps to reproduce:
- Select artboard(s)
- On Plugin, select Miro > Sync selected artboards
- Authenticate on Miro (with SSO)

Expected result: display list of Miro boards for sync

Actual result: "Connection error"" pop up displayed with the following message: "Sorry, the board list cannot be received"
<img width="327" alt="Capture d’écran 2022-02-10 à 14 03 58" src="https://user-images.githubusercontent.com/4620037/153456280-dc5152d2-4c86-42d6-9704-0ea1b9e8ba16.png">

Same issue reproduced on my colleagues laptops.

**Comment by ThibEko** [comment]
Nothing so far. Last Sketch updates didn't solve anything. Very frustrating.

**Comment by Tibb** [comment]
Nothing so far. Last Sketch updates didn't solve anything. Very frustrating.

**Comment by aromancev** [comment]
Hi all,

Sorry for the delay. Version `1.6.3` is now released, which fixes the issue.

**Comment by Tibb** [comment]
@aromancev works like a charm, thanks!
