### ISSUE TITLE
Uploads from Sketch to Miro cannot be moved, resized or deleted

### ISSUE THREAD

**Issue by satsumaII** [miroapp/sketch_plugin#27]
A large system update was performed by Miro last Saturday 18th June 22. We first noticed the below issue on the 20th June.

How to repeat the issue
-----------------------

1. Install the latest Sketch to Miro plugin 1.6.5 in Sketch (Version 89)
2. Place some content in an artboard in Sketch
3. Create a Miro board using a Miro account.
4. Using the Miro plugin in Sketch, sync the artboard to the new Miro board - using the following settings:
"Only selected artboards on this page"
"Export @2 and scale to 50% on canvas"

Issue
---------
Resizing the synced image in Miro is not possible (it always reverts to the previous size)
Deleting the image in Miro is not possible
Moving the image is also not possible (after screen refresh the image returns to its first position)

**Comment by IonLzr** [comment]
I had this problem too, with Sketch 88.1 and plugin 1.6.4
A silly workaround seems to exists if you're in an emergency:
- Sync artboards
- See result in Miro
- Restart Miro
- Modification of the artboards seems to be possible again.
This is really annoying though.

**Comment by inderjits1** [comment]
This was resolved a while back.
